name: food_frenzy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
#  path_provider: ^2.1.1
#  http: ^1.1.0
#  flutter_background_geolocation: '^4.12.0'
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  fluttertoast: ^8.1.2
#  sensors: ^2.0.3
  shared_preferences: ^2.2.1
  share: ^2.0.4
  url_launcher: ^6.0.6
  flutter_svg: ^2.0.7
  get: ^4.6.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shake: ^2.2.0
  sliding_up_panel: ^2.0.0+1
#  firebase_core: ^2.17.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dummy/
    - assets/icon/
    - assets/icon/onboarding/
    - assets/restaurant/
    - assets/restaurant/logo/
    - assets/restaurant/product/
    - assets/restaurant/product/paeng/
    - assets/voucher/

