// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOa7-3UZr2hyNawe5IbD0hBraKfCp3iak',
    appId: '1:295226228787:web:1670528d1ef8824ceae346',
    messagingSenderId: '295226228787',
    projectId: 'shake-eat-app',
    authDomain: 'shake-eat-app.firebaseapp.com',
    storageBucket: 'shake-eat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBXMBnZ2Ti_Wg3Tx3XfzuPJy1CG_hJzs',
    appId: '1:295226228787:android:669d27d28cb17396eae346',
    messagingSenderId: '295226228787',
    projectId: 'shake-eat-app',
    storageBucket: 'shake-eat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpASb5-WCKNaJ5PWlwbZQJx0dQ8UmQ4mk',
    appId: '1:295226228787:ios:beb1957480eefa5beae346',
    messagingSenderId: '295226228787',
    projectId: 'shake-eat-app',
    storageBucket: 'shake-eat-app.appspot.com',
    iosBundleId: 'com.example.foodFrenzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpASb5-WCKNaJ5PWlwbZQJx0dQ8UmQ4mk',
    appId: '1:295226228787:ios:e0a1ffed8121313beae346',
    messagingSenderId: '295226228787',
    projectId: 'shake-eat-app',
    storageBucket: 'shake-eat-app.appspot.com',
    iosBundleId: 'com.example.foodFrenzy.RunnerTests',
  );
}
